[package]
name = "slice-deque"
version = "0.3.0"
edition = "2021"

[features]
default = ["use_std"]
unix_sysv = ["slice-ring-buffer/unix_sysv"]
use_std = ["slice-ring-buffer/use_std"]

[dependencies]
slice-ring-buffer = { version = "0.3.4", default-features = false }
